// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfX7cknruT-7xrVQTNjNJz70BnQdJEYtA',
    appId: '1:841494925269:android:017c83b0cd83b2212d775c',
    messagingSenderId: '841494925269',
    projectId: 'plantist-c0391',
    storageBucket: 'plantist-c0391.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJU17PBz2I-sMbu-2sr_WjSK4TnLdqm9M',
    appId: '1:841494925269:ios:251f99b88814eefb2d775c',
    messagingSenderId: '841494925269',
    projectId: 'plantist-c0391',
    storageBucket: 'plantist-c0391.appspot.com',
    iosBundleId: 'com.altay.plantistApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Ax4SZTQWI6kvnqu-TYwyCc_oGh1qklo',
    appId: '1:841494925269:web:aed5461b27779bea2d775c',
    messagingSenderId: '841494925269',
    projectId: 'plantist-c0391',
    authDomain: 'plantist-c0391.firebaseapp.com',
    storageBucket: 'plantist-c0391.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJU17PBz2I-sMbu-2sr_WjSK4TnLdqm9M',
    appId: '1:841494925269:ios:251f99b88814eefb2d775c',
    messagingSenderId: '841494925269',
    projectId: 'plantist-c0391',
    storageBucket: 'plantist-c0391.appspot.com',
    iosBundleId: 'com.altay.plantistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1Ax4SZTQWI6kvnqu-TYwyCc_oGh1qklo',
    appId: '1:841494925269:web:1013c8ef60d1786a2d775c',
    messagingSenderId: '841494925269',
    projectId: 'plantist-c0391',
    authDomain: 'plantist-c0391.firebaseapp.com',
    storageBucket: 'plantist-c0391.appspot.com',
  );

}